import type { Effort, EffortLevel, GuidePick, GuideProfession, GuideSource, GuideTool } from "@redrob-labs/ui";
import { z } from "zod";

import type { ModelRef } from "../../../app/types";
import { t, type Language } from "../../../i18n";
import { REDROB_BASE_URL, REDROB_PROVIDER_ID } from "../../domains/settings/redrob-provider";

/** The harness id of a pick that runs here, in Redrob Cowork. */
const REDROB_HARNESS = "redrob-desk";

/**
 * The research behind "By profession": each profession's top five tasks, and the five best models (or model
 * chains) for each task in English, Korean and Hindi, each with a monthly API cost, ranked again for each
 * deliverable the task makes. Generated by `scripts/model-guide/build.mjs` from a dated leaderboard snapshot;
 * every figure carries where it came from.
 */
const Kind = z.enum(["measured", "published", "derived", "estimate"]);
const Label = z.object({ en: z.string(), ko: z.string() });

const Source = z.object({
  label: z.string(),
  value: z.string(),
  kind: Kind,
  url: z.string().optional(),
  date: z.string(),
  /** On a price row: whose price. */
  model: z.string().optional(),
});

const Pick = z.object({
  id: z.string(),
  steps: z.array(z.object({ model: z.string(), effort: z.string().optional(), role: z.literal("image").optional() })),
  harness: z.string(),
  kind: Kind,
  score: z.object({ quality: z.number(), reliability: z.number(), speed: z.number(), cost: z.number(), ci: z.number() }),
  monthly: z.number(),
  monthlyKind: Kind,
  monthlyRange: z.tuple([z.number(), z.number()]),
  /** Every effort the first model runs at, cheapest first, with a month of the task at it. */
  efforts: z.array(z.tuple([z.string(), z.number()])),
  missing: z.array(z.string()),
  flags: z.array(z.string()),
  sources: z.array(Source),
  /** The same ranking on another product, shown greyed for comparison. */
  benchmark: z.boolean().optional(),
});

export const GuideResearch = z.object({
  asOf: z.string(),
  weights: z.object({ quality: z.number(), reliability: z.number(), speed: z.number(), cost: z.number() }),
  models: z.record(z.string(), z.string()),
  /**
   * Each ranked model's id in the Redrob catalogue, null where Redrob does not serve it. Optional: an edition
   * Console published before the catalogue was added has none.
   */
  catalogue: z.record(z.string(), z.string().nullable()).optional(),
  professions: z.array(
    z.object({
      id: z.string(),
      label: Label,
      tasks: z.array(
        z.object({
          id: z.string(),
          label: Label,
          runs: z.number(),
          tools: z.array(z.string()),
          /** The deliverables the task is ranked for, a subset of GUIDE_OUTPUTS. */
          outputs: z.array(z.string()),
          picks: z.record(z.string(), z.array(Pick)),
          /** By output, then by working language. */
          picksByOutput: z.record(z.string(), z.record(z.string(), z.array(Pick))),
        }),
      ),
    }),
  ),
});
export type GuideResearch = z.infer<typeof GuideResearch>;
type ResearchPick = z.infer<typeof Pick>;

/** The working languages the research ranks, in the order the select shows them. */
export const GUIDE_LANGUAGES = ["en", "ko", "hi"] as const;

export function guideLanguages(): Array<{ value: string; label: string }> {
  return [
    { value: "en", label: t("desk.guide_language_en") },
    { value: "ko", label: t("desk.guide_language_ko") },
    { value: "hi", label: t("desk.guide_language_hi") },
  ];
}

/** The deliverables a task can be re-ranked for, in the order the select shows them. */
const OUTPUTS: Record<string, () => string> = {
  documents: () => t("desk.guide_output_documents"),
  presentations: () => t("desk.guide_output_presentations"),
  spreadsheets: () => t("desk.guide_output_spreadsheets"),
  graphics: () => t("desk.guide_output_graphics"),
  web: () => t("desk.guide_output_web"),
};

export function guideOutputs(): Array<{ value: string; label: string }> {
  return Object.entries(OUTPUTS).map(([value, label]) => ({ value, label: label() }));
}

/** Display names for the research's ids. Static keys, so the i18n audit can see every one. */
const EFFORTS: Record<string, () => string> = {
  none: () => t("desk.guide_effort_none"),
  minimal: () => t("desk.guide_effort_minimal"),
  low: () => t("desk.guide_effort_low"),
  medium: () => t("desk.guide_effort_medium"),
  high: () => t("desk.guide_effort_high"),
  xhigh: () => t("desk.guide_effort_xhigh"),
  max: () => t("desk.guide_effort_max"),
  default: () => t("desk.guide_effort_default"),
};

const HARNESSES: Record<string, () => string> = {
  "redrob-desk": () => t("desk.guide_harness_redrob-desk"),
  "chatgpt-work": () => t("desk.guide_harness_chatgpt-work"),
  "claude-cowork": () => t("desk.guide_harness_claude-cowork"),
};

const TOOLS: Record<string, () => string> = {
  browser: () => t("desk.guide_tool_browser"),
  calendar: () => t("desk.guide_tool_calendar"),
  "code-execution": () => t("desk.guide_tool_code-execution"),
  crm: () => t("desk.guide_tool_crm"),
  email: () => t("desk.guide_tool_email"),
  "file-read": () => t("desk.guide_tool_file-read"),
  "graphic-design": () => t("desk.guide_tool_graphic-design"),
  "pdf-generation": () => t("desk.guide_tool_pdf-generation"),
  presentation: () => t("desk.guide_tool_presentation"),
  spreadsheet: () => t("desk.guide_tool_spreadsheet"),
  "ui-ux-design": () => t("desk.guide_tool_ui-ux-design"),
  "web-search": () => t("desk.guide_tool_web-search"),
};

const FLAGS: Record<string, () => string> = {
  "close-call": () => t("desk.guide_flag_close-call"),
  "partly-estimated": () => t("desk.guide_flag_partly-estimated"),
  "outside-us": () => t("desk.guide_flag_outside-us"),
  "data-policy-unverified": () => t("desk.guide_flag_data-policy-unverified"),
  retiring: () => t("desk.guide_flag_retiring"),
};

/** An id the app has no name for shows as itself rather than as a missing-key path. */
function named(names: Record<string, () => string>, id: string): string {
  return names[id]?.() ?? id;
}

function effortName(effort: string): string {
  return named(EFFORTS, effort);
}

/** The ranked effort on the first model's own scale, and every level a reader can try. */
function efforts(pick: ResearchPick): { effort?: Effort; efforts: EffortLevel[] } {
  const ranked = pick.steps[0]?.effort;
  const of = pick.efforts.length;
  const levels = pick.efforts.map(([label, monthly], i) => ({ label: effortName(label), level: i + 1, of, monthly }));
  const at = pick.efforts.findIndex(([label]) => label === ranked);
  if (!ranked) return { efforts: levels };
  return { effort: at < 0 ? { label: effortName(ranked) } : { label: effortName(ranked), level: at + 1, of }, efforts: levels };
}

function sourceLabel(source: z.infer<typeof Source>, models: Record<string, string>): string {
  switch (source.label) {
    case "price":
      return t("desk.guide_source_price", { model: models[source.model ?? ""] ?? source.model ?? "" });
    case "monthly":
      return t("desk.guide_source_monthly");
    case "image":
      return t("desk.guide_source_image");
    default:
      return source.label;
  }
}

/** The research pick each shown pick came from, so "Use this" reads ids rather than display names. */
const SOURCE = new WeakMap<GuidePick, ResearchPick>();

/** What "Use this" does with a pick: the Redrob model and level new chats start on, or why it cannot. */
export type GuideUse =
  | { ok: true; model: ModelRef; variant: string | null; name: string; effort: string | null }
  | { ok: false; reason: "elsewhere"; name: string; harness: string }
  | { ok: false; reason: "not-on-redrob"; name: string };

/**
 * The model a pick runs, as the chat's model menu names it: provider `redrob` and the model's catalogue id, at
 * the level the reader tried or else the ranked one. A pick that runs on another product, or a model Redrob
 * does not serve, cannot be used. A pick that runs a text model then an image model starts the chat on the
 * text model: the chat has one model, and the levels belong to it.
 */
export function guideUse(research: GuideResearch, pick: GuidePick, tried: EffortLevel | null): GuideUse | null {
  const source = SOURCE.get(pick);
  const first = source?.steps[0];
  if (!source || !first) return null;
  const name = research.models[first.model] ?? first.model;
  if (source.harness !== REDROB_HARNESS) return { ok: false, reason: "elsewhere", name, harness: named(HARNESSES, source.harness) };
  const id = research.catalogue?.[first.model];
  if (!id) return { ok: false, reason: "not-on-redrob", name };
  const level = tried?.level ? source.efforts[tried.level - 1]?.[0] : undefined;
  const effort = level ?? first.effort ?? null;
  // "default" sends no level: the provider's own default, which is what an empty variant means.
  const variant = effort && effort !== "default" ? effort : null;
  return { ok: true, model: { providerID: REDROB_PROVIDER_ID, modelID: id }, variant, name, effort: variant ? effortName(variant) : null };
}

function toPick(pick: ResearchPick, tools: string[], research: GuideResearch): GuidePick {
  const name = (model: string) => research.models[model] ?? model;
  const sources: GuideSource[] = pick.sources.map((source) => ({
    label: sourceLabel(source, research.models),
    value: source.value,
    kind: source.kind,
    url: source.url,
    date: source.date,
  }));
  const evidence = pick.sources.filter((source) => !["price", "monthly", "image"].includes(source.label));
  const chain = pick.steps.length > 1;
  const ranked = efforts(pick);
  const shown: GuidePick = {
    id: pick.id,
    ...(chain
      ? {
          steps: pick.steps.map((step, i) => ({
            model: name(step.model),
            // The first step is the model the efforts belong to, so it carries the same meter.
            effort: i === 0 ? ranked.effort : step.effort ? { label: effortName(step.effort) } : undefined,
            role: t(step.role === "image" ? "desk.guide_role_image" : "desk.guide_role_text"),
          })),
        }
      : { model: name(pick.steps[0]?.model ?? "") }),
    harness: named(HARNESSES, pick.harness),
    kind: pick.kind,
    score: pick.score,
    monthly: pick.monthly,
    monthlyKind: pick.monthlyKind,
    monthlyRange: pick.monthlyRange,
    tools: tools.map(
      (tool): GuideTool => ({
        label: named(TOOLS, tool),
        missing: pick.missing.includes(tool),
      }),
    ),
    flags: pick.flags.map((flag) => named(FLAGS, flag)),
    why: evidence
      .slice(0, 2)
      .map((source) => `${source.label}: ${source.value}`)
      .join("; "),
    sources,
    ...(pick.benchmark ? { benchmark: true } : {}),
    ...ranked,
  };
  SOURCE.set(shown, pick);
  return shown;
}

/** The research as ModelGuide professions, labelled in the app's language. */
export function guideProfessions(research: GuideResearch, locale: Language): GuideProfession[] {
  return research.professions.map((profession) => ({
    id: profession.id,
    label: profession.label[locale],
    tasks: profession.tasks.map((task) => {
      const byLanguage = (picks: Record<string, ResearchPick[]>) =>
        Object.fromEntries(
          Object.entries(picks).map(([language, list]) => [language, list.map((pick) => toPick(pick, task.tools, research))]),
        );
      const ranked = byLanguage(task.picks);
      return {
        id: task.id,
        label: task.label[locale],
        title: task.label[locale],
        usage: t("desk.guide_usage", { count: task.runs }),
        picks: ranked.en,
        picksByLanguage: ranked,
        picksByOutput: Object.fromEntries(Object.entries(task.picksByOutput).map(([output, picks]) => [output, byLanguage(picks)])),
      };
    }),
  }));
}

/** Where Console publishes the edition Redrob Auto routes on. Unauthenticated, like `/pricing`. */
export const REDROB_GUIDE_URL = `${REDROB_BASE_URL}/guide`;

/**
 * The research, as Redrob Auto routes on it: Console's live edition (`GET /v1/guide`), so the ranking
 * a person reads here is the one their requests are routed by. Console keeps only the picks it can
 * route (the `redrob-desk` harness), so a pick ranked on another harness is not listed.
 *
 * The bundled copy below is still the published source Console syncs from, and is what this shows
 * when Console cannot be reached, which is a guide that may be a month behind rather than no guide.
 * Loaded on demand: it is a few megabytes, and only `/guide` reads it.
 */
export async function loadGuideResearch(fetchImpl?: typeof fetch): Promise<GuideResearch> {
  if (fetchImpl) {
    try {
      const response = await fetchImpl(REDROB_GUIDE_URL, { method: "GET", headers: { accept: "application/json" } });
      if (response.ok) {
        const live = GuideResearch.safeParse(await response.json());
        if (live.success) return live.data;
      }
    } catch {
      // Offline, or Console is having a moment: the bundled edition below.
    }
  }
  const module = await import("./model-guide.json");
  return GuideResearch.parse(module.default);
}
