/*
 * Writes ./vectors/vectors.json: signed policies and the verdict every verifier must reach on
 * them. redrob-server checks them in team-policy.test.ts; the console's policy API (redrob-console
 * K2) copies the file and asserts its signer produces policies this verifier accepts and its
 * verifier, if any, refuses the same bad ones.
 *
 * ECDSA signatures are randomised, so rerunning changes every `jws` while every verdict stays the
 * same. Run: bun src/team-policy/generate-vectors.ts (from apps/server)
 */
import { writeFile } from "node:fs/promises";
import { join } from "node:path";

import { samplePolicy, signTestPolicy } from "./test-signer.js";

const b64 = (value: string) => Buffer.from(value).toString("base64url");

const valid = await signTestPolicy(samplePolicy());
const [validHeader, validPayload, validSignature] = valid.split(".") as [string, string, string];
const unsigned = (header: Record<string, unknown>) =>
  `${b64(JSON.stringify(header))}.${validPayload}.${validSignature}`;

const vectors = [
  { name: "valid, active key", jws: valid, expect: { ok: true, accountId: "acc_vectors", version: 1 } },
  {
    name: "valid, standby key, version 2",
    jws: await signTestPolicy(samplePolicy({ version: 2 }), { kid: "test-2026-10-standby" }),
    expect: { ok: true, accountId: "acc_vectors", version: 2 },
  },
  {
    name: "payload changed after signing",
    jws: `${validHeader}.${b64(JSON.stringify(samplePolicy({ privacy: { ...samplePolicy().privacy, locked: false } })))}.${validSignature}`,
    expect: { ok: false, code: "team_policy_bad_signature" },
  },
  {
    name: "signed by the standby key but claims the active kid",
    jws: await signTestPolicy(samplePolicy(), { kid: "test-2026-10-active", signWith: "test-2026-10-standby" }),
    expect: { ok: false, code: "team_policy_bad_signature" },
  },
  {
    name: "kid this app does not pin",
    jws: await signTestPolicy(samplePolicy(), { kid: "test-unknown" }),
    expect: { ok: false, code: "team_policy_unknown_key" },
  },
  { name: "alg none", jws: unsigned({ alg: "none", typ: "redrob-team-policy+jws", kid: "test-2026-10-active" }), expect: { ok: false, code: "team_policy_bad_algorithm" } },
  { name: "alg HS256", jws: unsigned({ alg: "HS256", typ: "redrob-team-policy+jws", kid: "test-2026-10-active" }), expect: { ok: false, code: "team_policy_bad_algorithm" } },
  { name: "wrong typ", jws: await signTestPolicy(samplePolicy(), { header: { typ: "JWT" } }), expect: { ok: false, code: "team_policy_malformed" } },
  { name: "crit header", jws: await signTestPolicy(samplePolicy(), { header: { crit: ["exp"] } }), expect: { ok: false, code: "team_policy_malformed" } },
  {
    name: "signed but carries an unknown field",
    jws: await signTestPolicy({ ...samplePolicy(), expiresAt: "2027-01-01T00:00:00Z" }),
    expect: { ok: false, code: "team_policy_invalid" },
  },
  {
    name: "signed but schema version 1, with playbooks",
    jws: await signTestPolicy({
      ...samplePolicy(),
      v: 1,
      playbooks: [{ name: "weekly-update", description: "Weekly update", template: "Write this week's update." }],
    }),
    expect: { ok: false, code: "team_policy_unsupported_version" },
  },
  {
    name: "signed but schema version 3",
    jws: await signTestPolicy({ ...samplePolicy(), v: 3 }),
    expect: { ok: false, code: "team_policy_unsupported_version" },
  },
  {
    name: "schema version 2 but still carries playbooks",
    jws: await signTestPolicy({ ...samplePolicy(), playbooks: [] }),
    expect: { ok: false, code: "team_policy_unsupported_version" },
  },
  { name: "two segments", jws: `${validHeader}.${validPayload}`, expect: { ok: false, code: "team_policy_malformed" } },
];

const path = join(import.meta.dir, "vectors", "vectors.json");
await writeFile(
  path,
  JSON.stringify({ "//": "Generated by generate-vectors.ts. Signed with the TEST keys in test-keys.json.", vectors }, null, 2) + "\n",
);
console.log(`Wrote ${vectors.length} vectors to ${path}`);
