/*
 * Training examples for the work classifier: data analysis, finance, building, fixing, reviewing
 * and testing code, and design. Written for training only; see train/index.ts.
 */
import type { TrainingRows } from "./types.js";

export const SHEET_CODE_DESIGN: TrainingRows = {
  analyze: {
    en: [
      "Which regions grew fastest last quarter? Data attached.",
      "Analyze this CSV of signups and tell me where users drop off",
      "Build a cohort retention table from the attached export",
      "What's driving the increase in support tickets? Here's the data.",
      "Look at the sales numbers and find our best performing product line",
      "Calculate win rates by sales rep from this spreadsheet",
      "Find outliers in this expense data",
      "Compare conversion rates between the two landing page variants",
      "Analyze the NPS responses by customer segment",
      "Create a chart of monthly active users from this sheet",
      "Is there a correlation between seat count and churn in this data?",
      "Segment our customers by usage and revenue",
      "Analyze average deal size over time from the CRM export",
      "Which features are used most? Event data attached.",
      "Build a pivot of revenue by plan and month",
      "analyze this survey data and give me the main findings",
      "Check the funnel numbers, where's the biggest drop?",
      "Forecast next quarter's signups from the last two years of data",
      "Calculate customer acquisition cost by channel",
      "Analyze the A/B test results and tell me if it's significant",
      "What's our median response time per support agent? Sheet attached.",
      "Look at inventory levels and flag items running low",
      "Analyze the website traffic sources for the last 90 days",
      "Find which customers are at risk based on declining usage",
      "Build a summary table of headcount by department over time",
      "Analyze time-to-close for deals by industry",
      "Calculate the lifetime value by plan tier",
      "Find the busiest hours for support tickets",
      "Analyze the price sensitivity from these quote results",
      "Clean up this dataset and compute the weekly averages",
    ],
    ko: [
      "지난 분기에 어느 지역이 가장 빨리 성장했어? 데이터 첨부했어",
      "가입자 CSV 분석해서 어디서 이탈하는지 알려줘",
      "첨부 데이터로 코호트 리텐션 표 만들어 주세요",
      "고객 문의가 늘어난 원인이 뭔지 데이터 보고 분석해줘",
      "매출 수치 보고 제일 잘 나가는 제품군 찾아 주세요",
      "이 스프레드시트로 영업 담당자별 수주율 계산해줘",
      "경비 데이터에서 이상치 찾아줘",
      "랜딩 페이지 두 가지 버전의 전환율 비교해 주세요",
      "고객 세그먼트별 NPS 응답 분석",
      "이 시트로 월간 활성 사용자 차트 만들어줘",
      "좌석 수랑 이탈 사이에 상관관계 있는지 봐 주세요",
      "사용량이랑 매출로 고객 세그먼트 나눠줘",
      "CRM 내보내기로 평균 계약 규모 추이 분석해 주세요",
      "어떤 기능이 제일 많이 쓰이는지 이벤트 데이터 보고 알려줘",
      "요금제별 월별 매출 피벗 만들어줘",
      "이 설문 데이터 분석해서 주요 결과 알려 주세요",
      "퍼널 수치 봐줘. 제일 많이 빠지는 데가 어디야",
      "지난 2년 데이터로 다음 분기 가입자 수 예측해 주세요",
      "채널별 고객 획득 비용 계산해줘",
      "A/B 테스트 결과 분석해서 유의미한지 알려 주세요",
      "상담원별 응답 시간 중앙값 계산해줘. 시트 첨부",
      "재고 수준 보고 부족한 품목 표시해 주세요",
      "최근 90일 웹사이트 유입 경로 분석해줘",
      "사용량이 줄어드는 위험 고객 찾아 주세요",
      "부서별 인원 추이 요약 표 만들어줘",
      "업종별 계약 성사까지 걸리는 기간 분석해 주세요",
      "요금제 등급별 고객 생애 가치 계산",
      "고객 문의가 제일 몰리는 시간대 찾아줘",
      "견적 결과로 가격 민감도 분석해 주세요",
      "이 데이터셋 정리하고 주간 평균 계산해줘",
    ],
  },
  finance: {
    en: [
      "Reconcile the Stripe payouts with our bank deposits for October",
      "Match these vendor invoices to the purchase orders and flag mismatches",
      "Close the books for September: list unreconciled items",
      "Check whether the credit card statement matches the expense reports",
      "Find duplicate payments in the accounts payable ledger",
      "Reconcile intercompany balances between the US and Korea entities",
      "Verify the VAT amounts on these invoices",
      "Tie out the payroll journal to the bank transfers",
      "Check this invoice from the agency against our contract rates",
      "Prepare the month-end accrual entries from this list",
      "Reconcile the deferred revenue schedule with billing",
      "Match the customer payments to open invoices",
      "Find which expenses are missing receipts",
      "Reconcile the petty cash log",
      "Check the vendor statement against our AP balance",
      "reconcile accounts receivable aging with the GL",
      "Validate the totals on this batch of supplier invoices",
      "Compare the budget to actuals for marketing and explain the variance",
      "Reconcile the fixed asset register with depreciation",
      "Check whether we've been double-billed by the cloud provider",
      "Match corporate card transactions to employees",
      "Prepare the bank reconciliation for the operating account",
      "Check the sales tax collected against what we filed",
      "Reconcile refunds issued against the payment processor report",
      "Verify the exchange rates used on the foreign currency invoices",
      "Find unapplied cash in the receivables",
      "Reconcile the subscription revenue in the CRM with the accounting system",
      "Check that every PO over $10k has an approval",
      "Review this month's journal entries for errors",
      "Reconcile the expense report totals with the reimbursement payments",
    ],
    ko: [
      "10월 스트라이프 정산금이랑 은행 입금 내역 대사해줘",
      "공급업체 송장을 발주서와 맞춰 보고 안 맞는 거 표시해 주세요",
      "9월 결산해야 해. 대사 안 된 항목 정리해줘",
      "법인카드 명세서가 경비 보고서랑 맞는지 확인해 주세요",
      "매입채무 원장에서 중복 지급 찾아줘",
      "미국 법인과 한국 법인 간 내부 거래 잔액 대사",
      "이 세금계산서들 부가세 금액 검증해 주세요",
      "급여 분개를 은행 이체 내역과 맞춰줘",
      "대행사 청구서를 계약 단가와 대조해 주세요",
      "이 목록으로 월말 미지급 비용 분개 만들어줘",
      "선수수익 스케줄을 청구 내역과 대사해 주세요",
      "고객 입금을 미수 송장에 매칭해줘",
      "영수증이 빠진 경비 찾아 주세요",
      "소액 현금 장부 대사해줘",
      "거래처 잔액 확인서를 우리 매입채무 잔액과 대조",
      "매출채권 연령 분석을 총계정원장과 대사해줘",
      "공급업체 송장 묶음 합계 검증해 주세요",
      "마케팅 예산 대비 실적 비교하고 차이 설명해줘",
      "고정자산 대장을 감가상각 내역과 대사해 주세요",
      "클라우드 업체가 이중 청구했는지 확인해줘",
      "법인카드 거래를 직원별로 매칭해 주세요",
      "운영 계좌 은행 잔액 조정표 만들어줘",
      "징수한 부가세가 신고한 금액과 맞는지 확인해 주세요",
      "환불 처리 내역을 결제대행사 리포트와 대사해줘",
      "외화 송장에 적용된 환율 검증해 주세요",
      "매출채권에서 미적용 입금 찾아줘",
      "CRM 구독 매출을 회계 시스템과 대사해 주세요",
      "천만 원 넘는 발주서마다 승인 있는지 확인해줘",
      "이번 달 분개 오류 있는지 검토해 주세요",
      "경비 보고서 합계를 지급한 금액과 대사해줘",
    ],
  },
  code: {
    en: [
      "Add pagination to the /v1/orders endpoint",
      "Implement CSV export for the reports page",
      "Build a settings screen where users can change their notification preferences",
      "Create a React hook that debounces search input",
      "Add a webhook that fires when a subscription is cancelled",
      "Write a migration that adds an archived flag to projects",
      "Implement dark mode support in the web app",
      "Add rate limiting middleware to the API",
      "Create a CLI command that seeds the local database",
      "Build an endpoint that returns usage per day for a workspace",
      "Integrate Stripe checkout into the upgrade flow",
      "Add a background job that sends weekly digest emails",
      "Implement role-based access control for the admin pages",
      "Refactor the auth module so the token logic lives in one place",
      "Add file upload with drag and drop to the composer",
      "Create a Terraform module for the staging environment",
      "Build a Slack bot that posts deploy notifications",
      "add a search bar to the members table that filters by email",
      "Implement soft delete for comments",
      "Write a script that backfills the new column for existing rows",
      "Add OpenTelemetry tracing to the payment service",
      "Build the onboarding wizard component with three steps",
      "Add caching to the product catalogue endpoint",
      "Implement the forgot password flow end to end",
      "Port this Python script to TypeScript",
      "Add support for Korean in the date formatting helper",
      "Create a GitHub Action that runs the linter on pull requests",
      "Implement infinite scroll on the activity feed",
      "Build an export to Google Sheets integration",
      "Add an API for creating teams, with validation",
    ],
    ko: [
      "/v1/orders 엔드포인트에 페이지네이션 추가해줘",
      "리포트 페이지에 CSV 내보내기 구현해 주세요",
      "사용자가 알림 설정을 바꿀 수 있는 설정 화면 만들어줘",
      "검색 입력에 디바운스 거는 React 훅 만들어 주세요",
      "구독이 해지되면 호출되는 웹훅 추가해줘",
      "프로젝트에 보관 여부 플래그 추가하는 마이그레이션 작성",
      "웹앱에 다크 모드 지원 구현해 주세요",
      "API에 요청 제한 미들웨어 추가해줘",
      "로컬 DB에 시드 데이터 넣는 CLI 명령어 만들어 주세요",
      "워크스페이스별 일일 사용량을 돌려주는 엔드포인트 개발해줘",
      "업그레이드 흐름에 스트라이프 결제 연동해 주세요",
      "주간 요약 메일 보내는 백그라운드 작업 추가해줘",
      "관리자 페이지에 역할 기반 권한 제어 구현",
      "토큰 로직이 한 군데 있도록 인증 모듈 리팩터링해 주세요",
      "작성창에 드래그 앤 드롭 파일 업로드 추가해줘",
      "스테이징 환경용 테라폼 모듈 만들어 주세요",
      "배포 알림 올리는 슬랙 봇 만들어줘",
      "멤버 표에 이메일로 거르는 검색창 추가해줘",
      "댓글 소프트 삭제 구현해 주세요",
      "기존 행에 새 컬럼 값 채우는 백필 스크립트 작성해줘",
      "결제 서비스에 OpenTelemetry 트레이싱 추가",
      "3단계짜리 온보딩 마법사 컴포넌트 만들어 주세요",
      "상품 목록 엔드포인트에 캐시 넣어줘",
      "비밀번호 찾기 기능 처음부터 끝까지 구현해 주세요",
      "이 파이썬 스크립트 타입스크립트로 옮겨줘",
      "날짜 포맷 헬퍼에 한국어 지원 추가해 주세요",
      "PR마다 린터 돌리는 깃허브 액션 만들어줘",
      "활동 피드에 무한 스크롤 구현해 주세요",
      "구글 시트로 내보내는 연동 기능 개발",
      "팀 생성 API 추가해줘. 입력 검증 포함해서",
    ],
  },
  fix: {
    en: [
      "The login page throws a 500 when the email has a plus sign, fix it",
      "Users report the export button does nothing in Firefox. Find and fix the bug.",
      "Fix the memory leak in the websocket handler",
      "Why does the build fail on CI but pass locally? Fix it.",
      "The date picker shows the wrong month in January, fix it",
      "Fix the race condition when two people edit the same document",
      "The cron job runs twice every night, figure out why and fix it",
      "Prod is down, the API returns 502 for every request. Help me find the cause.",
      "Fix the N+1 query that's slowing down the dashboard",
      "The dark mode toggle resets after refresh, fix it",
      "This TypeError keeps showing up in Sentry, here's the stack trace",
      "Fix the broken image uploads on iOS Safari",
      "The total on the invoice is off by one cent, find the rounding bug",
      "Search returns no results for Korean queries, fix it",
      "fix the flaky timeout in the checkout service",
      "Our deploy is stuck rolling back, help me debug",
      "The app crashes when the user has no profile picture",
      "Fix the CORS error the frontend gets when calling the API",
      "Emails aren't being sent since this morning's release, find out why",
      "The pagination skips a record between pages, fix it",
      "Fix the off-by-one error in the retry logic",
      "Database CPU is at 100% since the last migration, help me find the cause",
      "The modal can't be closed with the Escape key, fix it",
      "Webhooks are being delivered out of order, debug it",
      "Fix the segfault in the image processing worker",
      "Login works on staging but not production, figure out what's different",
      "The chart renders blank when there's only one data point",
      "Fix the hydration mismatch warning on the pricing page",
      "Users in New York see yesterday's date in the report, fix the timezone bug",
      "Our health check keeps failing after deploy, investigate",
    ],
    ko: [
      "이메일에 + 들어가면 로그인 페이지가 500 에러나. 고쳐줘",
      "파이어폭스에서 내보내기 버튼이 안 먹는대요. 버그 찾아서 고쳐 주세요",
      "웹소켓 핸들러 메모리 누수 수정해줘",
      "CI에서는 빌드 실패하고 로컬에서는 되는데 왜 그래? 고쳐줘",
      "1월에 날짜 선택기가 엉뚱한 달을 보여 줘요. 수정해 주세요",
      "두 사람이 같은 문서 편집할 때 경쟁 조건 문제 고쳐줘",
      "크론 작업이 매일 밤 두 번씩 돌아. 원인 찾아서 고쳐줘",
      "운영 서버 다운됐어. API가 전부 502 반환해. 원인 찾는 거 도와줘",
      "대시보드 느리게 만드는 N+1 쿼리 고쳐 주세요",
      "새로고침하면 다크 모드 설정이 풀려. 수정해줘",
      "센트리에 이 TypeError가 계속 떠. 스택 트레이스 첨부할게",
      "iOS 사파리에서 이미지 업로드 깨지는 거 고쳐 주세요",
      "청구서 합계가 1원씩 틀려. 반올림 버그 찾아줘",
      "한국어로 검색하면 결과가 안 나와. 고쳐줘",
      "결제 서비스 간헐적 타임아웃 고쳐줘",
      "배포 롤백이 멈춰 있어. 디버깅 도와줘",
      "프로필 사진 없는 사용자면 앱이 죽어요",
      "프론트에서 API 호출할 때 나는 CORS 에러 수정해 주세요",
      "오늘 아침 배포 이후로 메일이 안 나가. 원인 알아봐줘",
      "페이지 넘길 때 레코드 하나가 빠져. 페이지네이션 고쳐줘",
      "재시도 로직의 off-by-one 오류 수정해 주세요",
      "지난 마이그레이션 이후로 DB CPU가 100%야. 원인 찾아줘",
      "ESC 키로 모달이 안 닫혀요. 고쳐 주세요",
      "웹훅이 순서가 뒤바뀌어서 전달돼. 디버깅해줘",
      "이미지 처리 워커 세그폴트 수정",
      "스테이징에서는 로그인 되는데 운영에서는 안 돼. 뭐가 다른지 찾아줘",
      "데이터가 하나뿐이면 차트가 빈 화면으로 나와요",
      "가격 페이지 하이드레이션 불일치 경고 고쳐줘",
      "뉴욕 사용자한테 리포트 날짜가 어제로 보여. 시간대 버그 수정해 주세요",
      "배포 후에 헬스 체크가 계속 실패해. 확인해줘",
    ],
  },
  review: {
    en: [
      "Review my PR and tell me what to change before I ask for approval",
      "Look at this diff and check for security issues",
      "Code review this function for readability",
      "Is this migration safe? Review it.",
      "Review the error handling in this service",
      "Go through this pull request and leave comments like a senior reviewer would",
      "Check this change for performance problems",
      "Review the new API design in this PR",
      "Is there anything wrong with this SQL query?",
      "review the tests in this PR, are they meaningful?",
      "Review this Dockerfile for best practices",
      "Look over the changes to the auth middleware",
      "Can you review the React component I just wrote?",
      "Check this PR for breaking changes to the public API",
      "Review the concurrency handling in this code",
      "Review the Terraform plan before I apply it",
      "Check whether this change handles null inputs",
      "Review my implementation of the caching layer",
      "Is the naming in this module consistent? Review it.",
      "Review the accessibility of this new form component",
      "Look at the diff for the payment refactor and spot regressions",
      "Review this regex, will it catch all the cases?",
      "Review the dependency upgrades in this PR",
      "Review this GraphQL schema change",
      "Look over the logging changes and tell me if we leak PII",
      "Review the config changes for the production rollout",
      "review this shell script before I run it on the server",
      "Check this PR follows our style guide",
      "Review the database indexes added in this change",
      "Review my teammate's PR on the billing module",
    ],
    ko: [
      "승인 요청하기 전에 내 PR 리뷰하고 고칠 점 알려줘",
      "이 diff 보안 문제 있는지 검토해 주세요",
      "이 함수 가독성 관점으로 코드 리뷰해줘",
      "이 마이그레이션 안전해? 리뷰해 줘",
      "이 서비스의 에러 처리 리뷰해 주세요",
      "시니어 리뷰어처럼 이 PR 보고 코멘트 남겨줘",
      "이 변경에 성능 문제 있는지 봐 주세요",
      "이 PR의 새 API 설계 리뷰",
      "이 SQL 쿼리 잘못된 거 있어?",
      "이 PR 테스트 의미 있는지 리뷰해줘",
      "이 Dockerfile 모범 사례 기준으로 리뷰해 주세요",
      "인증 미들웨어 변경사항 검토해줘",
      "방금 짠 React 컴포넌트 리뷰해 줄래?",
      "이 PR에 공개 API 호환성 깨지는 변경 있는지 봐 주세요",
      "이 코드 동시성 처리 리뷰해줘",
      "적용하기 전에 테라폼 플랜 리뷰해 주세요",
      "이 변경이 null 입력 처리하는지 확인해줘",
      "캐시 레이어 구현한 거 리뷰해 주세요",
      "이 모듈 네이밍 일관성 있는지 리뷰",
      "새 폼 컴포넌트 접근성 리뷰해줘",
      "결제 리팩터링 diff 보고 회귀 문제 찾아 주세요",
      "이 정규식 모든 경우 다 잡는지 검토해줘",
      "이 PR 의존성 업그레이드 리뷰해 주세요",
      "GraphQL 스키마 변경 리뷰해줘",
      "로깅 변경사항 보고 개인정보 새는 거 없는지 봐 주세요",
      "운영 배포용 설정 변경 리뷰",
      "서버에서 돌리기 전에 이 셸 스크립트 검토해줘",
      "이 PR 우리 스타일 가이드 지키는지 확인해 주세요",
      "이 변경에서 추가한 DB 인덱스 리뷰해줘",
      "동료가 올린 결제 모듈 PR 리뷰해 주세요",
    ],
  },
  test: {
    en: [
      "Write unit tests for the invoice calculator",
      "Add tests for the edge cases in the date parser",
      "Write an integration test for the signup API",
      "Create Playwright tests for the login flow",
      "Our coverage on the billing module is 30%, add tests",
      "Write a test that reproduces the bug before we fix it",
      "Add snapshot tests for the email templates",
      "Write property-based tests for the sorting function",
      "Write tests that cover the permission checks for each role",
      "Set up a load test for the search endpoint",
      "Write Jest tests for this React component",
      "Add regression tests for the timezone handling",
      "Write a contract test between the web app and the API",
      "Create test fixtures for the order processing tests",
      "write tests for the retry logic using a fake clock",
      "Add end-to-end tests for the checkout with a test card",
      "Write pytest tests for the data pipeline transforms",
      "Mock the payment provider and test the failure paths",
      "Write tests for the CSV importer with malformed files",
      "Add a test that fails if the migration drops a column",
      "Write tests for the webhook signature verification",
      "Create a test plan for the release",
      "Write tests for the rate limiter, including the boundary",
      "Add Cypress tests for the admin dashboard",
      "Write unit tests for the currency formatting helper with Korean won",
      "Write tests that check the API returns 403 for other workspaces",
      "Add tests for concurrency in the inventory reservation",
      "Write tests for the search ranking with sample documents",
      "Add a smoke test that runs after every deploy",
      "Write tests for the password strength validator",
    ],
    ko: [
      "청구 금액 계산기 단위 테스트 작성해줘",
      "날짜 파서 예외 케이스 테스트 추가해 주세요",
      "가입 API 통합 테스트 작성",
      "로그인 흐름 Playwright 테스트 만들어줘",
      "결제 모듈 커버리지가 30%야. 테스트 추가해 주세요",
      "고치기 전에 버그 재현하는 테스트부터 써줘",
      "메일 템플릿 스냅샷 테스트 추가",
      "정렬 함수 속성 기반 테스트 작성해 주세요",
      "역할별 권한 검사를 다 커버하는 테스트 써줘",
      "검색 엔드포인트 부하 테스트 세팅해 주세요",
      "이 React 컴포넌트 Jest 테스트 작성해줘",
      "시간대 처리 회귀 테스트 추가해 주세요",
      "웹앱과 API 사이 계약 테스트 작성",
      "주문 처리 테스트용 픽스처 만들어줘",
      "가짜 시계로 재시도 로직 테스트 써줘",
      "테스트 카드로 결제 E2E 테스트 추가해 주세요",
      "데이터 파이프라인 변환 pytest 테스트 작성",
      "결제 대행사 목 만들어서 실패 경로 테스트해줘",
      "잘못된 형식 파일로 CSV 가져오기 테스트 작성해 주세요",
      "마이그레이션이 컬럼을 지우면 실패하는 테스트 추가",
      "웹훅 서명 검증 테스트 써줘",
      "이번 릴리스 테스트 계획 만들어 주세요",
      "경계값 포함해서 요청 제한기 테스트 작성해줘",
      "관리자 대시보드 Cypress 테스트 추가해 주세요",
      "원화 통화 포맷 헬퍼 단위 테스트 써줘",
      "다른 워크스페이스 접근 시 API가 403 주는지 테스트 작성해 주세요",
      "재고 예약 동시성 테스트 추가해줘",
      "샘플 문서로 검색 랭킹 테스트 작성",
      "배포할 때마다 도는 스모크 테스트 추가해 주세요",
      "비밀번호 강도 검사기 테스트 써줘",
    ],
  },
  design: {
    en: [
      "Design a dashboard layout for the analytics page",
      "Mock up a mobile onboarding flow, three screens",
      "Create an illustration for the empty inbox state",
      "Design an icon set for the file types we support",
      "Make a poster for the hackathon",
      "Design the settings page in our design system",
      "Create a wireframe for the new checkout",
      "Design a banner for the conference booth",
      "Redesign the pricing table to make the recommended plan stand out",
      "Make a social media graphic for the product launch",
      "Design a logo concept for the internal tool",
      "Create a style guide page for our brand colors and fonts",
      "Design the email template header",
      "Mock up a data table with filters and bulk actions",
      "design a slide template for the sales deck",
      "Create three visual directions for the rebrand",
      "Design the error page with a friendly illustration",
      "Make an infographic from these survey results",
      "Design an app icon in a few variations",
      "Design a modal for confirming account deletion",
      "Create a hero image for the blog post",
      "Design a dark mode version of the sidebar",
      "Design a dashboard widget showing usage trends",
      "Mock up the Korean version of the landing page",
      "Design an onboarding checklist component",
      "Create a thumbnail for the YouTube tutorial",
      "Design packaging for the swag kit",
      "Make a flowchart diagram of the signup process for the docs",
      "Design the notification center dropdown",
      "Create a visual for the annual report cover",
    ],
    ko: [
      "분석 페이지 대시보드 레이아웃 디자인해줘",
      "모바일 온보딩 화면 세 개 시안 만들어 주세요",
      "받은편지함 빈 화면 일러스트 그려줘",
      "지원하는 파일 형식별 아이콘 세트 디자인",
      "해커톤 포스터 만들어 주세요",
      "디자인 시스템에 맞춰 설정 페이지 디자인해줘",
      "새 결제 화면 와이어프레임 그려 주세요",
      "컨퍼런스 부스 배너 디자인",
      "추천 요금제가 눈에 띄게 가격표 다시 디자인해줘",
      "제품 출시용 SNS 그래픽 만들어 주세요",
      "사내 도구 로고 시안 디자인해줘",
      "브랜드 색상과 폰트 스타일 가이드 페이지 만들어 주세요",
      "메일 템플릿 헤더 디자인",
      "필터랑 일괄 작업 있는 데이터 표 시안 만들어줘",
      "영업 자료 슬라이드 템플릿 디자인해 주세요",
      "리브랜딩 비주얼 방향 세 가지 만들어줘",
      "친근한 일러스트 들어간 에러 페이지 디자인",
      "설문 결과로 인포그래픽 만들어 주세요",
      "앱 아이콘 몇 가지 버전으로 디자인해줘",
      "계정 삭제 확인 모달 디자인해 주세요",
      "블로그 글 대표 이미지 만들어줘",
      "사이드바 다크 모드 버전 디자인",
      "사용량 추이 보여 주는 대시보드 위젯 디자인해 주세요",
      "랜딩 페이지 한국어 버전 시안 만들어줘",
      "온보딩 체크리스트 컴포넌트 디자인",
      "유튜브 튜토리얼 썸네일 만들어 주세요",
      "굿즈 키트 패키지 디자인해줘",
      "문서에 넣을 가입 절차 흐름도 그려 주세요",
      "알림 센터 드롭다운 디자인해줘",
      "연간 보고서 표지 비주얼 만들어 주세요",
    ],
  },
};
