/*
 * Training examples for the work classifier: plans and specs, marketing copy, contracts and
 * policies, and people documents. Written for training only; see train/index.ts.
 */
import type { TrainingRows } from "./types.js";

export const WRITE_B: TrainingRows = {
  spec: {
    en: [
      "Write a PRD for bulk user import",
      "Draft a project plan for migrating our billing system, with phases",
      "Turn these notes into a one-pager describing the feature and its goals",
      "Write the requirements for the new reporting dashboard",
      "Create a roadmap for the next two quarters from this list of ideas",
      "Write a design doc for adding SSO, including open questions",
      "Plan the launch: workstreams, owners, and dates",
      "Draft acceptance criteria for these user stories",
      "Write a spec for the mobile offline mode",
      "Break this initiative into milestones and estimate each",
      "Outline the scope for v1 of the partner portal, what's in and out",
      "Write an RFC proposing we move from REST to GraphQL",
      "Make a project plan for the office move with a timeline",
      "Draft the problem statement and success metrics for this feature",
      "Write a technical proposal for rate limiting per workspace",
      "plan next sprint from the backlog below",
      "Write user stories for the checkout redesign",
      "Turn this brainstorm into a prioritized feature list with rationale",
      "Draft a rollout plan with a beta, a staged release and a rollback step",
      "Write a spec for the notification preferences page",
      "Create a work breakdown for the data warehouse project",
      "Draft a decision memo comparing three options for search",
      "Plan the Q3 OKRs for the platform team",
      "Write the functional spec for exporting audit logs",
      "Outline a migration plan from the old CRM, with risks",
      "Draft a product brief for the AI assistant feature",
      "Write requirements for the admin role permissions",
      "Create a timeline for the hiring plan next half",
      "Write a spec covering the edge cases for subscription upgrades",
      "Plan the deprecation of the v1 API, with communication steps",
    ],
    ko: [
      "사용자 일괄 가져오기 PRD 써줘",
      "결제 시스템 이전 프로젝트 계획을 단계별로 세워 주세요",
      "이 메모를 기능과 목표를 설명하는 한 장짜리 문서로 만들어줘",
      "새 리포트 대시보드 요구사항 작성",
      "아이디어 목록으로 다음 두 분기 로드맵 만들어 주세요",
      "SSO 추가 설계 문서 써줘. 미결 질문도 포함해서",
      "출시 계획 세워줘. 업무 갈래, 담당자, 날짜",
      "이 유저 스토리들에 인수 조건 써 주세요",
      "모바일 오프라인 모드 기획서 작성",
      "이 과제를 마일스톤으로 나누고 각각 공수 추정해줘",
      "파트너 포털 v1 범위 정리해 주세요. 포함과 제외",
      "REST에서 GraphQL로 옮기자는 RFC 써줘",
      "사무실 이전 일정이 들어간 프로젝트 계획 만들어줘",
      "이 기능의 문제 정의와 성공 지표 초안을 써 주세요",
      "워크스페이스별 요청 제한 기술 제안서 작성",
      "아래 백로그로 다음 스프린트 계획 짜줘",
      "결제 화면 개편 유저 스토리 써 주세요",
      "브레인스토밍 결과를 근거와 함께 우선순위 매긴 기능 목록으로 정리해줘",
      "베타, 단계별 배포, 롤백까지 들어간 출시 계획 초안",
      "알림 설정 페이지 기획서 써줘",
      "데이터 웨어하우스 프로젝트 작업 분해 구조 만들어 주세요",
      "검색 방식 세 가지를 비교하는 의사결정 문서 초안",
      "플랫폼팀 3분기 OKR 계획 세워줘",
      "감사 로그 내보내기 기능 명세서 작성해 주세요",
      "기존 CRM에서 옮기는 마이그레이션 계획을 리스크와 함께 정리해줘",
      "AI 어시스턴트 기능 제품 브리프 초안",
      "관리자 역할 권한 요구사항 써 주세요",
      "하반기 채용 계획 타임라인 만들어줘",
      "구독 업그레이드 예외 상황까지 다루는 기획서 작성",
      "v1 API 종료 계획을 공지 단계까지 포함해서 세워 주세요",
    ],
  },
  copy: {
    en: [
      "Write a blog post announcing our Series B",
      "Draft three headline options for the new landing page",
      "Write a LinkedIn post about our new Korean office",
      "Write product page copy for the analytics feature",
      "Come up with a tagline for the spring campaign",
      "Write a newsletter intro for this month's product updates",
      "Draft ad copy for Google search, three variants under 90 characters",
      "Write a case study page from this customer interview",
      "Write the hero section text for our homepage",
      "Write tweets announcing the launch, a thread of five",
      "Draft an email newsletter promoting the webinar",
      "Write copy for the pricing page explaining each plan",
      "Write an Instagram caption for the team offsite photo",
      "Draft a press release about the partnership",
      "Write microcopy for the empty state in the dashboard",
      "write a blog post about best practices for remote onboarding",
      "Rewrite our About page to sound less corporate",
      "Write copy for the app store listing",
      "Draft a launch announcement for our community forum",
      "Write the text for a promotional banner, short and punchy",
      "Write a thought leadership article for our CEO about AI at work",
      "Draft copy for the feature comparison page",
      "Write a product launch video script, 60 seconds",
      "Write the subject line and preview text for the campaign email",
      "Write a customer story blog post from these notes",
      "Draft social posts for the conference we're sponsoring",
      "Write copy for the signup page that improves conversion",
      "Write a short brand story for the investor deck",
      "Write the description for our YouTube channel",
      "Draft taglines in a playful tone for the summer sale",
    ],
    ko: [
      "시리즈 B 투자 유치 알리는 블로그 글 써줘",
      "새 랜딩 페이지 헤드라인 세 가지 안 만들어 주세요",
      "한국 사무소 오픈 소식 링크드인 게시글 써줘",
      "분석 기능 제품 페이지 문구 작성해 주세요",
      "봄 캠페인 태그라인 뽑아줘",
      "이번 달 제품 업데이트 뉴스레터 도입부 써 주세요",
      "구글 검색 광고 문구 세 가지, 45자 이내로",
      "이 고객 인터뷰로 고객 사례 페이지 써줘",
      "홈페이지 메인 영역 문구 작성",
      "출시 알리는 트윗 다섯 개짜리 스레드 써줘",
      "웨비나 홍보 뉴스레터 메일 초안 써 주세요",
      "요금제별로 설명하는 가격 페이지 문구 작성해줘",
      "팀 워크숍 사진에 붙일 인스타 캡션",
      "파트너십 보도자료 초안 써 주세요",
      "대시보드 빈 화면에 들어갈 안내 문구 써줘",
      "원격 온보딩 모범 사례 블로그 글 써줘",
      "회사 소개 페이지를 덜 딱딱하게 다시 써 주세요",
      "앱스토어 등록 문구 작성",
      "커뮤니티 포럼에 올릴 출시 공지 초안",
      "프로모션 배너 문구, 짧고 강렬하게",
      "대표님 명의로 일하는 방식과 AI에 대한 기고문 써 주세요",
      "기능 비교 페이지 문구 초안",
      "60초짜리 제품 출시 영상 대본 써줘",
      "캠페인 메일 제목이랑 미리보기 문구 써 주세요",
      "이 메모로 고객 이야기 블로그 글 써줘",
      "후원하는 컨퍼런스 홍보용 SNS 게시물 초안",
      "가입 전환율 높일 가입 페이지 문구 써 주세요",
      "투자 제안서에 넣을 짧은 브랜드 스토리 작성",
      "유튜브 채널 소개글 써줘",
      "여름 세일 태그라인을 발랄한 톤으로 만들어 주세요",
    ],
  },
  policy: {
    en: [
      "Review this vendor agreement and flag anything unusual",
      "Check the indemnity clause in this contract against our standard terms",
      "Draft a data processing agreement for a new customer",
      "Does this NDA restrict us from hiring their employees? Point to the clause.",
      "Write an acceptable use policy for company laptops",
      "Review the customer's redlines on our MSA",
      "Draft an internal policy on expense approvals",
      "What are the termination rights in this agreement?",
      "Write a security policy for handling customer data",
      "Compare this SaaS agreement with our template and list the differences",
      "Draft a code of conduct for our community",
      "Review the liability cap in this contract",
      "Write a travel policy for employees",
      "Check this lease agreement for renewal terms and notice periods",
      "draft a privacy policy for our mobile app",
      "Is there anything risky in this partnership agreement?",
      "Write the open source usage policy for engineering",
      "Review the SLA terms the customer is asking for",
      "Draft a policy on using generative AI tools at work",
      "Summarize the obligations we take on in this contract and flag the risky ones",
      "Write a password and access policy",
      "Review the reseller agreement payment terms",
      "Draft a whistleblower policy",
      "Check if this contract has an auto-renewal clause",
      "Write a records retention policy",
      "Review this employment contract template for problems",
      "Draft a remote work equipment policy",
      "Check the governing law and jurisdiction in this agreement",
      "Write the incident response policy for the security team",
      "Review the change of control clause in the investment agreement",
    ],
    ko: [
      "이 공급 계약서 검토하고 이상한 부분 표시해줘",
      "이 계약의 면책 조항을 우리 표준 약관과 비교해 주세요",
      "신규 고객용 개인정보 처리 위탁 계약서 초안",
      "이 비밀유지계약 때문에 그쪽 직원을 채용 못 하는지 해당 조항 짚어줘",
      "회사 노트북 사용 정책 써 주세요",
      "고객이 우리 기본계약서에 수정 표시한 부분 검토해줘",
      "경비 승인 사내 규정 초안 작성",
      "이 계약에서 해지 권한이 어떻게 돼 있어?",
      "고객 데이터 취급 보안 정책 써 주세요",
      "이 SaaS 계약을 우리 템플릿과 비교해서 차이점 정리해줘",
      "커뮤니티 행동 강령 초안",
      "이 계약서 책임 한도 검토해 주세요",
      "직원 출장 규정 작성해줘",
      "임대차 계약서 갱신 조건이랑 통지 기간 확인해 주세요",
      "모바일 앱 개인정보 처리방침 초안",
      "이 제휴 계약에 위험한 부분 있어?",
      "개발팀 오픈소스 사용 정책 써 주세요",
      "고객이 요구하는 SLA 조건 검토해줘",
      "업무 중 생성형 AI 도구 사용 정책 초안 작성",
      "이 계약에서 우리가 지는 의무를 정리하고 위험한 건 표시해 주세요",
      "비밀번호 및 접근 권한 정책 써줘",
      "리셀러 계약서 대금 지급 조건 검토",
      "공익 신고 정책 초안 써 주세요",
      "이 계약서에 자동 갱신 조항 있는지 확인해줘",
      "기록 보존 정책 작성",
      "근로계약서 템플릿 문제 있는지 검토해 주세요",
      "재택근무 장비 지원 규정 초안",
      "이 계약의 준거법이랑 관할 법원 확인해줘",
      "보안팀 사고 대응 정책 써 주세요",
      "투자 계약서의 경영권 변동 조항 검토해줘",
    ],
  },
  hr: {
    en: [
      "Write a job description for a product designer",
      "Draft interview questions for a senior data engineer",
      "Summarize the 360 feedback for this manager",
      "Write an onboarding checklist for new sales reps",
      "Draft a performance improvement plan for an underperforming engineer",
      "Write the offer letter for our new head of marketing",
      "Create a 90-day plan for a new engineering manager",
      "Write a job post for a part-time customer support agent",
      "Summarize the exit interview notes into themes",
      "Draft a promotion case for this engineer based on their achievements",
      "Write a career ladder for the design team",
      "Draft the rejection email for candidates who didn't make the final round",
      "Write a welcome message for a new hire's first day",
      "Summarize this quarter's employee engagement survey",
      "Write competencies for a team lead role",
      "Draft goals for my direct report for next half",
      "Write a reference check questionnaire",
      "Create an interview scorecard for the account executive role",
      "Write a job description for a Korean-speaking customer success manager",
      "Draft feedback for my report on their presentation skills",
      "Write the internship program description",
      "Summarize the candidates' interview feedback into a hiring decision memo",
      "Write an announcement that a team member is leaving",
      "Draft the parental leave section of the handbook",
      "write a JD for a backend intern",
      "Write a self-review based on these accomplishments",
      "Create onboarding training plan for the support team",
      "Draft a note to the team announcing two new hires",
      "Write a role description for a staff engineer",
      "Summarize the peer reviews into strengths and areas to grow",
    ],
    ko: [
      "UX 리서처 뽑는 공고문 작성해줘",
      "시니어 데이터 엔지니어 면접 질문 초안",
      "이 매니저의 다면 평가 결과 요약해 주세요",
      "신규 영업 사원 온보딩 체크리스트 작성",
      "성과가 낮은 엔지니어의 성과 개선 계획 초안",
      "새 마케팅 총괄님께 보낼 처우 안내서 써 주세요",
      "새 엔지니어링 매니저의 90일 계획 만들어줘",
      "파트타임 고객지원 상담원 채용 공고 작성",
      "퇴사 면담 메모를 주제별로 요약해 주세요",
      "이 엔지니어 성과를 바탕으로 승진 추천서 초안",
      "디자인팀 커리어 레벨 체계 써줘",
      "최종 면접에서 떨어진 지원자들에게 보낼 불합격 메일 초안",
      "신입 첫 출근날 환영 메시지 써 주세요",
      "이번 분기 직원 몰입도 설문 결과 요약",
      "팀장 역할 역량 정의 작성해줘",
      "팀원 하반기 목표 초안 잡아 주세요",
      "평판 조회 질문지 만들어줘",
      "영업 담당자 직무 면접 평가표 만들어 주세요",
      "한국어 가능한 고객 성공 매니저 직무 기술서",
      "팀원에게 발표 역량에 대한 피드백 초안 써줘",
      "인턴십 프로그램 소개글 작성",
      "지원자 면접 피드백을 채용 결정 메모로 정리해 주세요",
      "팀원 퇴사 소식 공지 써줘",
      "취업 규칙에 들어갈 육아휴직 조항 초안",
      "백엔드 인턴 JD 써줘",
      "이 성과들로 자기 평가서 써 주세요",
      "고객지원팀 온보딩 교육 계획 만들어줘",
      "신규 입사자 두 명 소개하는 팀 공지 초안",
      "스태프 엔지니어 직무 설명 작성해 주세요",
      "동료 평가를 강점과 성장할 점으로 요약해줘",
    ],
  },
};
