/*
 * Training examples for the work classifier: support replies, summaries, customer email, research
 * and translation. Written for training only, apart from the evaluation set; see train/index.ts.
 */
import type { TrainingRows } from "./types.js";

export const WRITE_A: TrainingRows = {
  reply: {
    en: [
      "Customer can't log in after resetting their password, write them a reply",
      "Help me respond to a ticket asking why their invoice is higher this month",
      "Reply to this user who says the mobile app crashes on startup. Be empathetic and ask for their device model.",
      "Draft a response to a customer asking if we support SAML",
      "A customer wants to cancel. Write a reply that confirms the cancellation date and mentions they can export their data first.",
      "Write back to the ticket below, they're asking how to change the billing email",
      "answer this support question about rate limits",
      "Customer is frustrated that support took three days to respond. Write an apology and the answer to their original question.",
      "Need a reply to a ticket where the user accidentally deleted a project",
      "Write a short, friendly answer explaining that the feature they want is on the roadmap but has no date",
      "respond to the customer, tell them the outage is resolved and we'll credit their account",
      "Reply to this enterprise admin asking how to add 50 users at once",
      "Customer reports duplicate notifications. Draft a reply asking for screenshots and the time it happened.",
      "Can you write the support reply for ticket #4821? They want a refund for an unused month.",
      "help me answer a customer who thinks they were overcharged",
      "Draft a response saying we can't share their data with a third party, and explain why",
      "Write a reply to a user asking how to export their reports to PDF, step by step",
      "Customer says the integration with Slack stopped working. Reply with the fix: reconnect from Settings.",
      "Respond to a complaint about slow page loads, without promising a timeline",
      "Write the reply to this escalated ticket from our biggest account",
      "Draft an answer to a question about our data retention period",
      "A customer asked whether they can downgrade mid-cycle. Answer them.",
      "reply to this ticket in a calm tone, the customer is very angry",
      "Write a response that walks the user through resetting two-factor authentication",
      "Help me close out this ticket with a polite final reply",
      "Customer wants to know when their trial ends, reply with the date and how to upgrade",
      "Write a support reply explaining the error message they're seeing and what to try",
      "Respond to the user asking for an invoice with our tax ID on it",
      "Reply to a customer who sent a bug report with no details, asking for the steps to reproduce",
      "Draft the reply for a ticket about a failed payment, include the link to update the card",
    ],
    ko: [
      "비밀번호 재설정 후에 로그인이 안 된다는 고객 문의에 답장 써줘",
      "이번 달 청구서 금액이 왜 올랐냐는 문의에 답변 좀 도와줘",
      "앱이 시작하자마자 꺼진다는 사용자한테 답장 써 주세요. 공감하는 톤으로, 기기 모델도 물어봐 주세요.",
      "SAML 지원하냐는 고객 질문에 답변 초안",
      "해지하겠다는 고객에게 해지 날짜를 확인해 주고, 그 전에 데이터를 내보낼 수 있다고 안내하는 답장을 써 주세요.",
      "아래 티켓에 답장해줘. 결제 이메일 바꾸는 방법 묻는 거야",
      "요청 한도 관련 고객 문의에 답변해줘",
      "답변이 3일이나 늦었다고 화난 고객입니다. 사과와 함께 원래 질문에 대한 답을 써 주세요.",
      "프로젝트를 실수로 삭제했다는 고객 티켓 답장이 필요해",
      "원하는 기능이 로드맵에는 있지만 일정은 없다고 짧고 친절하게 답해 주세요",
      "장애 해결됐고 크레딧 넣어 드린다고 고객한테 답장해줘",
      "사용자 50명을 한 번에 추가하는 방법을 묻는 엔터프라이즈 관리자에게 답변해 주세요",
      "알림이 두 번씩 온다는 고객 신고예요. 스크린샷이랑 발생 시간 요청하는 답장 써 주세요.",
      "4821번 티켓 답장 써 줄래? 안 쓴 한 달 환불해 달래",
      "요금이 더 나갔다고 생각하는 고객한테 답변 좀",
      "고객 데이터를 제3자에게 공유할 수 없다는 내용과 이유를 설명하는 답장 초안",
      "리포트를 PDF로 내보내는 방법을 단계별로 안내하는 답변을 써 주세요",
      "슬랙 연동이 끊겼다는 고객에게 설정에서 다시 연결하면 된다고 답해줘",
      "페이지가 느리다는 불만에 일정은 약속하지 말고 답변해 주세요",
      "제일 큰 고객사에서 에스컬레이션된 티켓 답장 써줘",
      "데이터 보관 기간 묻는 문의에 답변 작성",
      "결제 주기 중간에 요금제를 낮출 수 있는지 묻는 고객에게 답해 주세요",
      "이 티켓 차분한 톤으로 답장해줘. 고객이 엄청 화났어",
      "2단계 인증 재설정 방법을 차례대로 안내하는 답장을 써 주세요",
      "이 티켓 마무리하는 정중한 마지막 답장 부탁해",
      "체험 기간 언제 끝나는지 묻는 고객에게 날짜랑 업그레이드 방법 알려 주는 답장",
      "고객이 보고 있는 오류 메시지가 뭔지 설명하고 해볼 방법을 안내하는 답변을 써 주세요",
      "사업자등록번호가 들어간 청구서를 요청한 고객에게 답장해줘",
      "재현 방법 없이 버그만 신고한 고객에게 재현 단계를 물어보는 답장",
      "결제 실패 티켓 답장 써줘. 카드 정보 바꾸는 링크도 넣고",
    ],
  },
  summ: {
    en: [
      "Summarize this Slack thread so I can catch up",
      "What were the decisions in this meeting? Transcript below.",
      "Give me a one-paragraph summary of the attached customer call",
      "Boil this 30-reply email chain down to what's still unresolved",
      "summarize the notes from today's standup",
      "Write a short recap of the incident channel for people who missed it",
      "Turn this interview transcript into five key takeaways",
      "Summarize the support tickets from this week into themes",
      "Can you condense this long document into a page?",
      "Recap the board meeting notes in bullet points",
      "Summarize what the customer said on the call about pricing",
      "Give me the TL;DR of this RFC",
      "Pull the action items out of these meeting notes, with owners",
      "Summarize this week's activity across our top accounts",
      "Make a brief summary of the feedback survey responses",
      "Summarize this thread for my manager in three sentences",
      "What did we agree on in the call with the vendor? Here's the recording transcript.",
      "Condense the attached report into an executive summary",
      "summarize these customer reviews",
      "Write a digest of the product team's updates this sprint",
      "Summarize the Q&A from the all-hands",
      "I missed the planning meeting, summarize it for me from the notes",
      "Give me a quick summary of the ticket history before I take it over",
      "Summarize the key risks raised in this discussion",
      "Turn this voice memo transcript into tidy notes",
      "Summarize the comments on this pull request discussion",
      "Recap of yesterday's client workshop, please",
      "Summarize the main complaints in these app store reviews",
      "Shorten this status update to fit in one Slack message",
      "Summarize the user research sessions into findings",
    ],
    ko: [
      "이 슬랙 스레드 따라잡게 요약해줘",
      "이 회의에서 뭘 결정했는지 알려줘. 녹취록 아래에 있어",
      "첨부한 고객 통화를 한 문단으로 요약해 주세요",
      "답장 30개짜리 메일 스레드에서 아직 안 풀린 것만 정리해줘",
      "오늘 스탠드업 메모 요약",
      "장애 채널 내용을 못 본 사람들을 위해 짧게 정리해 주세요",
      "인터뷰 녹취록을 핵심 다섯 가지로 정리해 주세요",
      "이번 주 고객 문의 티켓들을 주제별로 요약해줘",
      "이 긴 문서 한 장으로 줄여 줄 수 있어?",
      "이사회 회의록을 글머리표로 정리해 주세요",
      "통화에서 고객이 가격에 대해 한 말만 요약해줘",
      "이 RFC 세 줄 요약",
      "회의 메모에서 담당자랑 같이 할 일만 뽑아줘",
      "주요 고객사들의 이번 주 활동을 요약해 주세요",
      "피드백 설문 응답 간단히 요약해줘",
      "이 스레드를 팀장님께 세 문장으로 요약해 드려야 해",
      "벤더랑 통화에서 뭐 합의했는지 정리해줘. 녹음 녹취록이야",
      "첨부한 보고서를 경영진용 요약으로 만들어 주세요",
      "고객 리뷰들 요약해줘",
      "이번 스프린트 제품팀 업데이트를 다이제스트로 정리해 주세요",
      "전사 미팅 Q&A 정리해줘",
      "기획 회의 못 들어갔는데 메모 보고 요약해 줘",
      "티켓 넘겨받기 전에 지금까지 이력 빠르게 요약해줘",
      "이 논의에서 나온 주요 리스크만 정리해 주세요",
      "음성 메모 녹취를 깔끔한 메모로 정리해줘",
      "이 PR 토론에 달린 의견들 요약",
      "어제 고객사 워크숍 내용 정리 부탁해요",
      "앱스토어 리뷰에서 주요 불만 사항만 요약해 주세요",
      "이 진행 상황 업데이트를 슬랙 메시지 하나 분량으로 줄여줘",
      "사용자 리서치 세션들을 발견점 위주로 정리해 주세요",
    ],
  },
  email: {
    en: [
      "Write an email to a customer letting them know their contract renews next month",
      "Draft a first outreach email to the head of IT at a hospital group",
      "Email the prospect we met at the conference and suggest a call next week",
      "Write a follow-up to the client who went quiet after our proposal",
      "Draft an email introducing our new account manager to the customer",
      "Write a thank-you email after the demo with a link to the recording",
      "Email the customer that their pilot ends Friday and ask whether they want to continue",
      "draft an upsell email for customers on the basic plan",
      "Write an email inviting our top customers to the user conference",
      "Compose an email to a lead asking who else should join the evaluation",
      "Write a polite chaser to a customer whose invoice is 30 days overdue",
      "Draft a customer email announcing the price change in March",
      "Write an email to a prospect who asked for a case study, attach the healthcare one",
      "email the customer the summary of what we agreed in today's meeting",
      "Draft a win-back email for customers who churned last quarter",
      "Write a short email asking a happy customer for a referral",
      "Draft an email to set up a quarterly business review with the client",
      "Write to the customer's procurement team with the documents they asked for",
      "Cold email for CFOs at mid-size retailers, under 100 words",
      "Write an email confirming the onboarding schedule with the customer",
      "Draft an email apologizing to the customer for the missed deadline",
      "Email the prospect a recap of the pricing options we discussed",
      "Write an email to a customer champion who just changed jobs",
      "Follow-up email after the trade show to everyone who visited our booth",
      "Write an email letting the customer know the feature they asked for has shipped",
      "Draft an email to re-engage a prospect who hasn't replied in two months",
      "Write a renewal email offering a discount for a two-year commitment",
      "Email the customer to schedule the security review call",
      "Draft a note to a customer explaining the changes to our support hours",
      "Write an introduction email from me to a potential partner",
    ],
    ko: [
      "다음 달에 계약이 갱신된다고 고객에게 알리는 메일 써줘",
      "병원 그룹 IT 책임자에게 보낼 첫 영업 메일 초안",
      "컨퍼런스에서 만난 잠재 고객에게 다음 주 통화를 제안하는 메일을 써 주세요",
      "제안서 보낸 뒤로 연락이 없는 고객에게 후속 메일 써줘",
      "새 담당 매니저를 고객에게 소개하는 메일 초안",
      "데모 후에 녹화 링크와 함께 보낼 감사 메일을 써 주세요",
      "파일럿이 금요일에 끝나는데 계속 쓸지 묻는 메일 고객한테 보내줘",
      "기본 요금제 고객 대상 업셀 메일 초안 써줘",
      "주요 고객사를 사용자 컨퍼런스에 초대하는 메일을 작성해 주세요",
      "도입 검토에 누가 더 참여해야 할지 묻는 메일을 리드에게 써줘",
      "청구서가 30일 연체된 고객에게 정중하게 독촉하는 메일",
      "3월 가격 변경을 안내하는 고객 메일 초안을 써 주세요",
      "사례 자료 요청한 잠재 고객에게 의료 사례 첨부해서 메일 써줘",
      "오늘 회의에서 합의한 내용 정리해서 고객한테 메일 보내줘",
      "지난 분기에 이탈한 고객을 다시 데려올 메일 초안",
      "만족한 고객에게 소개를 부탁하는 짧은 메일을 써 주세요",
      "고객사와 분기 비즈니스 리뷰 일정 잡는 메일 써줘",
      "고객사 구매팀이 요청한 서류를 보내는 메일을 작성해 주세요",
      "중견 유통사 재무 책임자 대상 콜드메일, 200자 이내로",
      "온보딩 일정을 고객과 확정하는 메일 써줘",
      "마감을 못 지킨 것에 대해 고객에게 사과하는 메일 초안을 써 주세요",
      "얘기 나눈 가격 옵션 정리해서 잠재 고객에게 메일로 보내줘",
      "이직한 고객사 담당자에게 보낼 메일 써줘",
      "전시회 부스 방문자 전원에게 보낼 후속 메일",
      "요청하신 기능이 출시됐다고 고객에게 알리는 메일을 써 주세요",
      "두 달째 답이 없는 잠재 고객 다시 연락하는 메일 초안",
      "2년 약정 시 할인해 준다는 갱신 메일 써줘",
      "보안 검토 통화 일정을 잡자는 메일을 고객에게 보내 주세요",
      "고객지원 운영 시간 변경을 설명하는 안내 메일 초안",
      "잠재 파트너사에 저를 소개하는 메일을 써 주세요",
    ],
  },
  research: {
    en: [
      "Find out everything public about this prospect before my meeting",
      "Research the top three vendors in our space and how they price",
      "Who are the decision makers at this company? Use LinkedIn and their website.",
      "Look into the regulations for selling software to banks in Singapore",
      "What's the latest news about our biggest customer?",
      "Research how competitors handle onboarding for enterprise customers",
      "Find market sizing data for HR software in Southeast Asia, with sources",
      "Dig into this startup's funding history and investors",
      "Give me background on this account: industry, size, tech stack",
      "research which companies recently adopted our competitor's product",
      "Find three examples of companies that publish their pricing for this kind of tool",
      "What are analysts saying about the AI coding assistant market this year?",
      "Look up the hiring trends at this company to see if they're growing",
      "Research industry benchmarks for SaaS churn in the mid-market",
      "Find out what tools this prospect currently uses for project management",
      "Put together a brief on the customer's recent acquisitions",
      "research the Japanese market for our product, regulations and competitors",
      "Find case studies from competitors in the logistics sector",
      "What are the main trends in customer support software? Cite sources.",
      "Look into this company's annual report and pull out their strategic priorities",
      "Research average contract values for tools like ours",
      "Find the conferences our target customers go to",
      "Investigate why a competitor raised their prices",
      "Who does this company partner with? Find their integrations and resellers.",
      "Research the procurement process at public universities in Korea",
      "Compare the feature sets of the leading alternatives",
      "Find reviews of our competitor on G2 and summarize the complaints",
      "Research this person before my call: role, background, recent posts",
      "Look up the market share of the top cloud providers in Korea",
      "Find out if this prospect has had any security incidents in the news",
    ],
    ko: [
      "미팅 전에 이 잠재 고객사에 대해 공개된 정보 전부 찾아줘",
      "우리 분야 상위 벤더 세 곳과 가격 정책을 조사해 주세요",
      "이 회사 의사결정권자가 누군지 링크드인이랑 홈페이지로 알아봐줘",
      "싱가포르 은행에 소프트웨어 팔 때 필요한 규제 조사",
      "가장 큰 고객사 최근 뉴스 뭐 있어?",
      "경쟁사들이 엔터프라이즈 온보딩을 어떻게 하는지 조사해 주세요",
      "동남아 HR 소프트웨어 시장 규모 자료를 출처와 함께 찾아줘",
      "이 스타트업 투자 이력이랑 투자사 알아봐줘",
      "이 고객사 배경 정리해 주세요. 업종, 규모, 기술 스택",
      "최근에 경쟁사 제품 도입한 회사들 조사해줘",
      "이런 종류 도구 중에 가격을 공개하는 회사 사례 세 개 찾아줘",
      "올해 AI 코딩 도구 시장에 대해 애널리스트들이 뭐라고 하는지 알려 주세요",
      "이 회사 채용 동향 보고 성장 중인지 알아봐줘",
      "중견기업 SaaS 이탈률 업계 벤치마크 조사",
      "이 잠재 고객이 지금 프로젝트 관리에 무슨 도구를 쓰는지 알아봐 주세요",
      "고객사가 최근 인수한 회사들에 대한 브리프 만들어줘",
      "우리 제품 일본 시장 조사해줘. 규제랑 경쟁사",
      "물류 업계 경쟁사 고객 사례 찾아 주세요",
      "고객지원 소프트웨어 주요 트렌드가 뭐야? 출처도 달아줘",
      "이 회사 연차보고서에서 전략 우선순위를 뽑아 주세요",
      "우리 같은 도구의 평균 계약 금액 조사해줘",
      "타깃 고객들이 가는 컨퍼런스 찾아줘",
      "경쟁사가 왜 가격을 올렸는지 알아봐 주세요",
      "이 회사 파트너사가 어디야? 연동이랑 리셀러 찾아줘",
      "국내 국립대 구매 절차 조사해 주세요",
      "주요 대안 제품들 기능 비교 조사",
      "G2에서 경쟁사 리뷰 찾아서 불만 사항 정리해줘",
      "통화 전에 이 사람 조사 좀. 직책, 경력, 최근 게시물",
      "국내 클라우드 사업자 시장 점유율 찾아 주세요",
      "이 잠재 고객사가 보안 사고로 뉴스에 난 적 있는지 알아봐줘",
    ],
  },
  translate: {
    en: [
      "Translate this email from the Japanese customer into English",
      "Put this release note into Korean",
      "Translate my reply into Korean, keep it formal",
      "Can you translate the attached contract summary into English?",
      "translate this to Spanish",
      "Translate the onboarding guide into Japanese, keep the screenshots' labels in English",
      "The customer wrote in Vietnamese, what does it say?",
      "Translate these 20 UI strings into Korean",
      "Make a Korean version of the FAQ page",
      "Translate the support macro into Korean and Japanese",
      "Translate this Korean feedback into English for the product team",
      "Please translate the help center article on billing into Korean",
      "What's this Chinese message from the partner saying?",
      "Translate our privacy notice into Korean",
      "Localize the welcome email for our Korean users",
      "Translate the meeting notes from Korean to English",
      "translate the attached slide text into English",
      "Translate this complaint into English and keep the tone",
      "Turn this English job post into natural Korean",
      "Translate the product description for the Japanese store listing",
      "Translate my answer back into the customer's language, which is German",
      "Translate this survey into Korean",
      "Translate the error messages file into Korean",
      "Rewrite this machine-translated paragraph into natural English",
      "Translate the terms of service changes into Korean",
      "Give me an English translation of this Korean tax notice",
      "Translate the chat transcript from Korean to English",
      "Translate these push notification texts into Korean, keep them short",
      "Translate the customer's PDF letter into English",
      "Localize the pricing page copy for Japan",
    ],
    ko: [
      "일본 고객이 보낸 메일 영어로 번역해줘",
      "이 릴리스 노트 한국어로 옮겨 주세요",
      "내 답장 격식 있게 영어로 번역해줘",
      "첨부한 계약 요약본을 영어로 번역해 주실 수 있나요?",
      "이거 스페인어로 번역",
      "온보딩 가이드를 일본어로 번역해 주세요. 스크린샷 라벨은 영어로 두고요",
      "고객이 베트남어로 썼는데 뭐라는 거야?",
      "UI 문구 20개 한국어로 번역해줘",
      "FAQ 페이지 영어판 만들어 주세요",
      "고객지원 매크로를 영어와 일본어로 번역해줘",
      "이 한국어 피드백을 제품팀용으로 영어로 번역해 주세요",
      "결제 관련 도움말 문서 영어로 번역 부탁드려요",
      "파트너사에서 온 중국어 메시지 무슨 내용이야?",
      "개인정보 처리방침 영어로 번역해 주세요",
      "한국 사용자용 환영 메일 현지화해줘",
      "회의록 한국어에서 영어로 번역",
      "첨부 슬라이드 텍스트 영어로 번역해줘",
      "이 불만 메일 영어로 번역해 주세요. 어조는 그대로",
      "영어 채용 공고를 자연스러운 한국어로 바꿔줘",
      "일본 스토어 등록용 제품 설명 번역해 주세요",
      "내 답변을 고객 언어인 독일어로 번역해줘",
      "이 설문 영어로 번역해 주세요",
      "오류 메시지 파일 한국어로 번역",
      "기계 번역된 문단을 자연스러운 한국어로 다시 써줘",
      "이용약관 변경 내용 영어로 번역해 주세요",
      "이 국세청 안내문 영어로 번역해줘",
      "채팅 기록 한국어에서 영어로 번역해 주세요",
      "푸시 알림 문구들 짧게 영어로 번역해줘",
      "고객이 보낸 PDF 서신 영어로 번역 부탁해요",
      "가격 페이지 문구를 일본 시장에 맞게 현지화해 주세요",
    ],
  },
};
